### ISSUE TITLE
Issue with .net core 3.0 Preview 1

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#108]
Today microsoft released the preview of .net core 3.0, i decided to give it a try but i get the following error:

```
Unhandled Exception: System.FieldAccessException: Cannot set initonly static field 'glGetError' after type 'Ultraviolet.OpenGL.Bindings.gl' is initialized.
   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at Ultraviolet.OpenGL.Bindings.gl.LoadFunction(IOpenGLInitializer initializer, FieldInfo field, Boolean checkRequirements) in F:\ultraviolet\Source\Ultraviolet.OpenGL.Bindings\Shared\gl.Initialization.cs:line 378
   at Ultraviolet.OpenGL.Bindings.gl.LoadFunction(IOpenGLInitializer initializer, String name, Boolean checkRequirements) in F:\ultraviolet\Source\Ultraviolet.OpenGL.Bindings\Shared\gl.Initialization.cs:line 339
   at Ultraviolet.OpenGL.Bindings.gl.Initialize(IOpenGLInitializer initializer) in F:\ultraviolet\Source\Ultraviolet.OpenGL.Bindings\Shared\gl.Initialization.cs:line 40
   at Ultraviolet.OpenGL.OpenGLUltravioletGraphics..ctor(OpenGLUltravioletContext uv, OpenGLUltravioletConfiguration configuration, Version versionRequested, Version versionRequired) in F:\ultraviolet\Source\Ultraviolet.OpenGL\Shar
ed\OpenGLUltravioletGraphics.cs:line 83
   at Ultraviolet.OpenGL.OpenGLUltravioletContext..ctor(IUltravioletHost host, OpenGLUltravioletConfiguration configuration) in F:\ultraviolet\Source\Ultraviolet.OpenGL\Shared\OpenGLUltravioletContext.cs:line 77
   at UvDebug.Game.OnCreatingUltravioletContext() in F:\ultraviolet\Source\UvDebug\Shared\Game.cs:line 87
   at Ultraviolet.UltravioletContext.EnsureSuccessfulCreation(Func`1 fn) in F:\ultraviolet\Source\Ultraviolet\Shared\UltravioletContext.cs:line 609
   at Ultraviolet.UltravioletApplication.CreateUltravioletContext() in F:\ultraviolet\Source\Ultraviolet.Shims.NETCore\UltravioletApplication.cs:line 583
   at Ultraviolet.UltravioletApplication.Run() in F:\ultraviolet\Source\Ultraviolet.Shims.NETCore\UltravioletApplication.cs:line 70
   at UvDebug.Game.Main(String[] args) in F:\ultraviolet\Source\UvDebug\Shared\Game.cs:line 54

```

**Comment by tlgkccampbell** [comment]
Interesting, that restriction doesn't exist in any other version of the runtime. I'm not sure whether to try to fix this in Ultraviolet or report it as a bug in .NET Core 3.0... 🤔

**Comment by tlgkccampbell** [comment]
I found [this issue](https://github.com/dotnet/coreclr/pull/20886) which indicates that this was a deliberate change, so I'll update Ultraviolet to address this in the near future.

**Comment by tlgkccampbell** [comment]
I just pushed a change to the `develop` branch which removes the `readonly` attribute from the OpenGL delegates. Let me know whether that fixes the issue.

**Comment by RUSshy** [comment]
Yes it works, ty :D
