### ISSUE TITLE
Version 1.3.13 No type named 'Generic' has been registered with the Presentation Foundation.

### ISSUE THREAD

**Issue by Scellow** [tlgkccampbell/ultraviolet#37]
In the release note i see the mention "The Generic class has been removed."

What does that mean?

I guess it has something to do with databinding, but i can't seems to find what is causing the error, compiler/debugger doesn't tell me who is the culprit ^^

**Comment by tlgkccampbell** [comment]
The `Generic` class provided some combined touch/mouse input events that didn't work very well, hence it being removed when I refactored the touch input API. It sounds like your UI is trying to handle an event that was defined on `Generic` (like `GenericInteraction`) but since that's been removed, it can't find the type anymore and data binding fails.

Can you provide any more information about what's happening, like a stack trace?

**Comment by Scellow** [comment]
OK i fixed it, i'm not sure how but it's fixed (i was binding a List to a ListView)

**Comment by Scellow** [comment]
Ok i have more info about this issue

I was using an old uvss stylesheet, the i was using the one from the sample before you made the change

So it probably also broke for lot of user, might worth it to catch the exception and give proper error message

Stack Trace:

```
Unhandled Exception: System.InvalidOperationException: No type named 'Generic' has been registered with the Presentation Foundation.
   at TwistedLogik.Ultraviolet.UI.Presentation.EventManager.FindByStylingName(UltravioletContext uv, DependencyObject dobj, String owner, String name)
   at TwistedLogik.Ultraviolet.UI.Presentation.Styles.UvssEventTrigger.Attach(DependencyObject dobj)
   at TwistedLogik.Ultraviolet.UI.Presentation.Styles.UvssStylePrioritizer.Apply(UIElement element)
   at TwistedLogik.Ultraviolet.UI.Presentation.Styles.UvssDocument.ApplyStylesInternal(UIElement element)
   at TwistedLogik.Ultraviolet.UI.Presentation.Styles.UvssDocument.ApplyStyles(UIElement element)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.ApplyStyles(UvssDocument document)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Style(UvssDocument styleSheet)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.OnVisualParentChangedInternal(Visual oldParent, Visual newParent)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.OnVisualParentChangedInternal(Visual oldParent, Visual newParent)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.Visual.AddVisualChild(Visual child)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualCollection.AddVisualChild(Visual child)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualCollection.Insert(Int32 index, Visual item)
   at TwistedLogik.Ultraviolet.UI.Presentation.Controls.UIElementCollection.Insert(Int32 index, UIElement item)
   at TwistedLogik.Ultraviolet.UI.Presentation.Controls.ItemsControl.AddItemContainer(Int32 index, Object item)
   at TwistedLogik.Ultraviolet.UI.Presentation.Controls.ItemsControl.ItemsCollectionReset(INotifyCollectionChanged collection)
   at TwistedLogik.Ultraviolet.UI.Presentation.Controls.ItemCollection.OnCollectionReset()
   at TwistedLogik.Ultraviolet.UI.Presentation.Controls.ItemCollection.SetItemsSource(IEnumerable itemsSource)
   at TwistedLogik.Ultraviolet.UI.Presentation.Controls.ItemsControl.HandleItemsSourceChanged(DependencyObject dobj, IEnumerable oldValue, IEnumerable newValue)
   at TwistedLogik.Ultraviolet.UI.Presentation.PropertyMetadata.HandleChanged[T](DependencyObject dobj, DependencyProperty dp, T oldValue, T newValue)
   at TwistedLogik.Ultraviolet.UI.Presentation.DependencyObject.DependencyPropertyValue`1.HandleChanged(T oldValue, T newValue)
   at TwistedLogik.Ultraviolet.UI.Presentation.DependencyObject.DependencyPropertyValue`1.CheckForChanges(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.DependencyObject.DependencyPropertyValue`1.Digest(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.DependencyObject.Digest(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.<>c.<UpdateOverride>b__125_0(UIElement child, Object state)
   at TwistedLogik.Ultraviolet.UI.Presentation.Media.VisualTreeHelper.ForEachChild[TChild](DependencyObject dobj, Object state, Action`2 action)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateOverride(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.FrameworkElement.UpdateCore(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.UIElement.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.Presentation.PresentationFoundationView.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.UIPanel.UpdateView(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.UIScreen.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.UIScreenStack.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UI.UltravioletUI.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.OpenGL.OpenGLUltravioletContext.Update(UltravioletTime time)
   at TwistedLogik.Ultraviolet.UltravioletHostCore.UpdateContext(UltravioletContext uv, UltravioletTime time)
   at TwistedLogik.Ultraviolet.UltravioletHostCore.RunOneTick()
   at TwistedLogik.Ultraviolet.UltravioletApplication.Run()
   at TheRoguer.Client.Legacy.Program.Main(String[] args) in C:\Users\Scellow\Projects\CS\theRoguer\TheRoguer.Client.Legacy\Program.cs:line 9
```

**Comment by tlgkccampbell** [comment]
I'll keep this in mind for the next release, thank you.
