### ISSUE TITLE
Unable to create UV context

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#49]
Hi,

I got my new computer but now i can't compile Uv anymore

It crash with the following: 

```make
System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at TwistedLogik.Nucleus.Text.LocalizationDatabase.GetCultureStrings(String culture) in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Nucleus\Text\LocalizationDatabase.cs:line 350
   at TwistedLogik.Nucleus.Text.LocalizationDatabase.Contains(String key) in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Nucleus\Text\LocalizationDatabase.cs:line 249
   at TwistedLogik.Ultraviolet.OpenGL.Platform.OpenGLUltravioletWindowInfo.InitializePrimaryWindow(OpenGLUltravioletConfiguration configuration) in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Ultraviolet.OpenGL\Platform\OpenGLUltravioletWindowInfo.cs:line 379
   at TwistedLogik.Ultraviolet.OpenGL.Platform.OpenGLUltravioletWindowInfo..ctor(UltravioletContext uv, OpenGLUltravioletConfiguration configuration) in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Ultraviolet.OpenGL\Platform\OpenGLUltravioletWindowInfo.cs:line 31
   at TwistedLogik.Ultraviolet.OpenGL.OpenGLUltravioletPlatform..ctor(UltravioletContext uv, OpenGLUltravioletConfiguration configuration) in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Ultraviolet.OpenGL\OpenGLUltravioletPlatform.cs:line 24
   at TwistedLogik.Ultraviolet.OpenGL.OpenGLUltravioletContext..ctor(IUltravioletHost host, OpenGLUltravioletConfiguration configuration) in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Ultraviolet.OpenGL\OpenGLUltravioletContext.cs:line 122
   at UvDebugSandbox.Game.OnCreatingUltravioletContext() in C:\Users\RUS\Projects\CS\dev\ultraviolet\UvDebugSandbox\Game.cs:line 76
   at TwistedLogik.Ultraviolet.UltravioletContext.EnsureSuccessfulCreation(Func`1 fn) in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Ultraviolet\UltravioletContext.cs:line 950
   at TwistedLogik.Ultraviolet.UltravioletApplication.CreateUltravioletContext() in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Ultraviolet\UltravioletApplication.cs:line 556
   at TwistedLogik.Ultraviolet.UltravioletApplication.Run() in C:\Users\RUS\Projects\CS\dev\ultraviolet\TwistedLogik.Ultraviolet\UltravioletApplication.cs:line 64
   at UvDebugSandbox.Game.Main(String[] args) in C:\Users\RUS\Projects\CS\dev\ultraviolet\UvDebugSandbox\Game.cs:line 51

```

**Comment by tlgkccampbell** [comment]
Which branch are you on?

**Comment by RUSshy** [comment]
i am on develop branch

**Comment by tlgkccampbell** [comment]
OK, I think I found the problem. Looks like there's a typo in some new fallback code I added to the localization system. I'll have a fix in shortly.

I was literally minutes away from pushing the 1.3.15 release out, so good timing. :)

**Comment by tlgkccampbell** [comment]
My latest commit to the development branch should fix this issue. Can you confirm?

**Comment by RUSshy** [comment]
yes it fixed it :D :D ty !!

**Comment by tlgkccampbell** [comment]
Great. Thanks for the bug report.

**Comment by RUSshy** [comment]
No problem :) 

What is new in the new version? i can now reload the UI without restart?

**Comment by tlgkccampbell** [comment]
Yes, although you have to make a couple of small changes to turn it on. The `UvDebugSandbox` application has been updated to enable the feature, if you need an example.

Please see [the release notes](https://github.com/tlgkccampbell/ultraviolet/releases/tag/v1.3.15) for more information.

**Comment by RUSshy** [comment]
I tried to follow the DebugSandbox project but if i edit the XML screen it doesn't change

I tried origin file, and the one in output folder

https://gist.github.com/RUSshy/52df02c8e14ff266b0ffc31360767422

What is weird is debugsanbox works, if i edit xml, i can see changes, but not my project :(

**Comment by tlgkccampbell** [comment]
Hmm... I will need to take some time to try to reproduce this locally. Let me know if you figure anything out in the meantime. [This](https://github.com/tlgkccampbell/ultraviolet/blob/v1.3.15/TwistedLogik.Ultraviolet/Content/WatchedAsset.cs#L80-L98) is the method which actually watches for changes in case you want to do some debugging yourself.

**Comment by RUSshy** [comment]
I don't know if this can help:
http://i.imgur.com/vIYpIab.png

So it is detected  that the asset changed but the ui doesn't reload

**Comment by RUSshy** [comment]
So here: https://github.com/tlgkccampbell/ultraviolet/blob/v1.3.15/TwistedLogik.Ultraviolet/Content/WatchedAsset.cs#L82

If i change:

if ((e.FullPath == AssetFilePath || Owner.IsWatchedDependencyPath(AssetPath, e.FullPath)) && OnReloading != null)


to


if (OnReloading != null)


Then it works :)

**Comment by RUSshy** [comment]
It works if i edit asset that is in output path only

Because my Content folder is in a different directory, and i copy it using the csproj:

```xml
  <Target Name="CopyData">
    <ItemGroup>
      <Data Include="$(SolutionDir)\data\**\*.*" />
    </ItemGroup>
    <Copy SkipUnchangedFiles="true" SourceFiles="@(Data)" DestinationFolder="$(OutputPath)data\%(RecursiveDir)" />
  </Target>
```

So maybe that is why it is not working?

**Comment by RUSshy** [comment]
Hot reload ui make it so easy to tweak/create UI when im not really good at WPF, thanks a lot for implementing it, making ui was a bit frustrating for me, but now it is going to be so easy, big thanks :) :)

**Comment by tlgkccampbell** [comment]
Modifying that line of code is a bad idea.  The file watcher tracks changes to the entire content directory, so without that filter it will reload all of your watched assets when *any* file changes. The `IsWatchedDependencyPath()` method allows it to link dependent files together, i.e. to make sure that your view is reloaded if you change one of the style sheet files.

The way that you're copying around your files is almost certainly the reason it's not working how you expect. Ultraviolet isn't smart enough -- and really can't be smart enough -- to figure out what you're doing, so it doesn't know where the original files live.

Ultraviolet's logic for trying to guess where your original files are is simple: it looks at the root directory of your content manager (i.e. "Content"), moves up two directories from the location of your .exe file (up through `bin/Debug`), and then looks for another directory with the same name as the content manager root ("Content"). If it doesn't find a match, it will only be able to watch for changes inside of your `bin` directory.

Is there a reason you have things set up this way?

**Comment by RUSshy** [comment]
I am setting it up that way because i need to share content between my client and my server and my editor XML/JSON/MAP(binary) data, i also changed the output path so i can reunite all my binaries, easier to browser

```
Solution/data/
Solution/src/ProjA
Solution/src/ProbB
Solution/src/ProjC
Solution/out/debug/ProjA/bin
Solution/out/debug/ProjB/bin
Solution/out/debug/ProjC/bin
```
But i think im just going to do the "normal" way, and create symlinks, i dont want to loose ability to use content watcher

**Comment by RUSshy** [comment]
In .NET Core it act like in Java, working directory is always the project directory, not bin/debug/ thing so it doesn't need to copy files away

Do you have plan to port to .NET Core in future?

**Comment by RUSshy** [comment]
Also is there a way to LoadWatched the content from the Manifest file ? like for the Texture of the screens
Or is there a way to avoid using Manifest file for UI texture ?

I tried to do that: 

            globalStyleSheet = new CompositeUvssDocument(Ultraviolet, reloadGlobalStyleSheet);
            globalStyleSheet.Append(ContentManager, "ui/DefaultUI");
            globalStyleSheet.Append(ContentManager, "ui/DefaultUIStyles");

but it doesn't work, it says: Unhandled Exception: System.InvalidOperationException: Could not find a valid processor for asset 'data\ui\DefaultUI.png'.

**Comment by tlgkccampbell** [comment]
I think that setting up symlinks is the way to go for your situation.

Regarding .NET Core: it's on my list of things that I need to eventually work on, but it probably won't happen in the immediate future.

Regarding watched manifests: no, at present there's no way to do that.  If you want the view to reload when a particular texture changes, you should be able to set it as a watched dependency using the `AddWatchedDependency()` method on `ContentManager`.  

I should probably handle that automatically for any resources which are used by the style sheet, but it got overlooked for 1.3.15.  I'll look into adding it in the next release.
